// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJGoFast.Data;

#nullable disable

namespace PJGoFast.Migrations
{
    [DbContext(typeof(PJGoFastDbContext))]
    [Migration("20260411141013_TayXe3")]
    partial class TayXe3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJGoFast.Models.Entities.Admin", b =>
                {
                    b.Property<string>("IdAdmin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdmin");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            IdAdmin = "TAOLACHUA",
                            HoVaTen = "Quản Trị Viên Mặc Định",
                            MatKhau = "$2y$10$AwT9qSEsKIrmPBEKGEY0geoqHAvYpgAkUU0a97AEF6y4iMTyN.LVG",
                            NgaySinh = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0987654321",
                            VaiTro = "QuanTri"
                        });
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.ChuyenDi", b =>
                {
                    b.Property<string>("IdChuyenDi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiemDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaTamTinh")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("GiaThucTe")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("HanNhanChuyen")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAdmin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdTX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiXeYeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdChuyenDi");

                    b.HasIndex("IdAdmin");

                    b.HasIndex("IdKH");

                    b.HasIndex("IdTX");

                    b.HasIndex("TrangThai", "ThoiGianTao");

                    b.ToTable("ChuyenDis");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.KhachHang", b =>
                {
                    b.Property<string>("IdKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdKH");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.NhatKy", b =>
                {
                    b.Property<string>("IdNhatKy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdChuyenDi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThucHienBoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhatKy");

                    b.HasIndex("IdChuyenDi", "ThoiGian");

                    b.ToTable("nhatKys");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.TaiXe", b =>
                {
                    b.Property<string>("IdTX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiemDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThaiHoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiOnline")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTX");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.HasIndex("TrangThaiOnline");

                    b.ToTable("TaiXes");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.ThanhToan", b =>
                {
                    b.Property<string>("IdThanhToan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdChuyenDi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("ThoiGianGhiNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThanhToan");

                    b.HasIndex("IdChuyenDi")
                        .IsUnique();

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.ChuyenDi", b =>
                {
                    b.HasOne("PJGoFast.Models.Entities.Admin", "Admin")
                        .WithMany("ChuyenDis")
                        .HasForeignKey("IdAdmin");

                    b.HasOne("PJGoFast.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("ChuyenDis")
                        .HasForeignKey("IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJGoFast.Models.Entities.TaiXe", "TaiXe")
                        .WithMany("ChuyenDis")
                        .HasForeignKey("IdTX");

                    b.Navigation("Admin");

                    b.Navigation("KhachHang");

                    b.Navigation("TaiXe");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.NhatKy", b =>
                {
                    b.HasOne("PJGoFast.Models.Entities.ChuyenDi", "ChuyenDi")
                        .WithMany("NhatKys")
                        .HasForeignKey("IdChuyenDi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenDi");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.ThanhToan", b =>
                {
                    b.HasOne("PJGoFast.Models.Entities.ChuyenDi", "ChuyenDi")
                        .WithOne("ThanhToan")
                        .HasForeignKey("PJGoFast.Models.Entities.ThanhToan", "IdChuyenDi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenDi");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.Admin", b =>
                {
                    b.Navigation("ChuyenDis");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.ChuyenDi", b =>
                {
                    b.Navigation("NhatKys");

                    b.Navigation("ThanhToan")
                        .IsRequired();
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("ChuyenDis");
                });

            modelBuilder.Entity("PJGoFast.Models.Entities.TaiXe", b =>
                {
                    b.Navigation("ChuyenDis");
                });
#pragma warning restore 612, 618
        }
    }
}
